<?php

declare(strict_types=1);
defined('ABSPATH') || exit;


require_once get_template_directory() . '/includes/theme-settings.php';


function sartorello_woo_theme_register_menus()
{
    register_nav_menus(
        array(
            'sartorello-woo-theme_furniture'  => __('Furniture Menu', 'sartorello-woo-theme'),
            'sartorello-woo-theme_decoration' => __('Decoration Menu', 'sartorello-woo-theme'),
            'sartorello-woo-theme_lighting'   => __('Lighting Menu', 'sartorello-woo-theme'),
        )
    );
}
add_action('after_setup_theme', 'sartorello_woo_theme_register_menus');


//========================================
// WooCommerce Support
//========================================
//
if (class_exists('WooCommerce')) {
    // Declare WooCommerce support for our theme.
    // WooCommerce template overrides are only enabled on themes that declare WooCommerce support.
    function declare_woocommerce_support()
    {
        add_theme_support('woocommerce');
    }
    add_action('after_setup_theme', 'declare_woocommerce_support');

    // Remove WooCommerce styles.
    // This is useful if you want to use your own styles instead of the default WooCommerce styles.
    add_filter('woocommerce_enqueue_styles', '__return_false');

    // Remove Page Title from WooCommerce pages.
    add_filter('woocommerce_show_page_title', '__return_false');
}


//========================================
// Enqueue custom scripts and styles
//========================================
//
function enqueue_styles_and_scripts(): void
{
    // Global Theme CSS (generated by Tailwind CSS)
    wp_enqueue_style('global-theme-styles', get_template_directory_uri() . '/assets/frontend/css/style.css');
    // Main JavaScript Bundle
    wp_enqueue_script('main-theme-js', get_template_directory_uri() . '/assets/frontend/js/bundle.js', [], null, true);

    // Enqueue scripts for single product pages
    if (is_product()) {
        // Resize Thumbnails Script
        wp_enqueue_script('resize-thumbnails', get_template_directory_uri() . '/assets/frontend/js/resize-thumbnails.js', [], null, true);
    }

    // *** Enqueue scripts for the checkout page ***
    // Note: The scripts are also enqueued on the account page because the billing and shipping fields are also used there.
    // This is necessary for the address autocomplete and person type visibility scripts to work correctly. 
    if (is_checkout() || is_account_page()) {
        // Checkout Address Autocomplete
        wp_enqueue_script('checkout-address-autocomplete', get_template_directory_uri() . '/assets/frontend/js/checkout-address-autocomplete.js', [], null, true);
        // Checkout Person Type Visibility
        wp_enqueue_script('checkout-person-type-visibility', get_template_directory_uri() . '/assets/frontend/js/checkout-person-type-visibility.js', [], null, true);
    }
}
add_action('wp_enqueue_scripts', 'enqueue_styles_and_scripts');


/**
 * Change the parameters for the "Related Products" section in single product pages 
 */
function change_related_products_args($args)
{
    $args['posts_per_page'] = 12;
    return $args;
}
add_filter('woocommerce_output_related_products_args', 'change_related_products_args');


/**
 * Add Tailwind CSS classes to WooCommerce cart item thumbnail images
 */
function add_tailwind_classes_to_cart_item_thumbnail($thumbnail, $cart_item, $cart_item_key)
{
    $tailwind_classes = 'size-full object-cover';
    $thumbnail = str_replace('class="', 'class="' . esc_attr($tailwind_classes) . ' ', $thumbnail);
    return $thumbnail;
}
add_filter('woocommerce_cart_item_thumbnail', 'add_tailwind_classes_to_cart_item_thumbnail', 10, 3);
